import tailwindForms from '@tailwindcss/forms';
import tailwindAnimation from 'tailwindcss-animated';
import defaultTheme from 'tailwindcss/defaultTheme';
import plugin from 'tailwindcss/plugin';

import button from './_button';
import card from './_card';
import color from './_colors';
import fonts from './_fonts';
import htmlBody from './_html-body';
import pageLayout from './_page-layout';

const cutomPlugins = plugin(function ({
  addBase,
  addUtilities,
  addComponents,
}) {
  addBase([htmlBody, fonts]);
  addUtilities({});
  addComponents([button, card, pageLayout]);
});

export default {
  theme: {
    extend: {
      borderColor: {
        DEFAULT: color?.white?.[400],
        subtle: color?.white?.[300],
        selected: color?.primary?.[600],
        light: color?.primary?.[100],
        brand: color?.primary?.[600],
        'brand-subtle': color?.primary?.[400],
        success: color?.green?.[600],
        'success-subtle': color?.green?.[400],
        info: color?.blue?.[600],
        'info-subtle': color?.blue?.[400],
        warning: color?.orange?.[200],
        'warning-subtle': color?.orange?.[400],
        danger: color?.red?.[400],
        'danger-subtle': color?.red?.[500],
      },
      backgroundColor: {
        interface: color?.white?.[100],
        'interface-subtle': color?.white?.[200],
        'interface-selected': color?.blue?.[400],
        'interface-pressed': color?.white?.[100],
        'interface-selected-subtle': color?.blue?.[50],
        'interface-active': color?.white?.[100],
        'interface-hovered': color?.white[100],
        'interface-disabled': color.white[300],
        'interface-light': color?.white?.[100],
        'interface-overlay': `rgba(var(${color?.black?.[50]}), .4)`,
        'status-neutral': color?.white?.[400],
        'status-success': color?.green?.[400],
        'status-warning': color?.orange?.[400],
        'status-danger': color?.red?.[400],
        inverse: color?.black?.[500],
        'inverse-hovered': color?.black?.[600],
        'inverse-pressed': color?.black?.[400],
        brand: color?.primary?.[700],
        'brand-hovered': color?.primary?.[800],
        'brand-pressed': color?.primary?.[900],
        'brand-subtle': color?.primary?.[50],
        'brand-hovered-subtle': color?.primary?.[100],
        'brand-pressed-subtle': color?.primary?.[200],
        info: color?.blue?.[700],
        'info-hovered': color?.blue?.[800],
        'info-pressed': color?.blue?.[900],
        'info-subtle': color?.blue?.[50],
        'info-hovered-subtle': color?.blue?.[100],
        'info-pressed-subtle': color?.blue?.[200],
        success: color?.green?.[600],
        'success-hovered': color?.green?.[700],
        'success-pressed': color?.green?.[800],
        'success-subtle': color?.green?.[50],
        'success-hovered-subtle': color?.green?.[100],
        'success-pressed-subtle': color?.green?.[200],
        warning: color?.orange?.[600],
        'warning-hovered': color?.orange?.[500],
        'warning-pressed': color?.orange?.[700],
        'warning-subtle': color?.orange?.[50],
        'warning-hovered-subtle': color?.orange?.[100],
        'warning-pressed-subtle': color?.orange?.[200],
        danger: color?.red?.[600],
        'danger-hovered': color?.red?.[500],
        'danger-pressed': color?.red?.[700],
        'danger-subtle': color?.red?.[50],
        'danger-hovered-subtle': color?.red?.[100],
        'danger-pressed-subtle': color?.red?.[200],
      },
      textColor: {
        DEFAULT: color?.black?.[800],
        inverse: color?.white?.[200],
        subtle: color?.white?.[1100],
        placeholder: color?.white?.[800],
        disabled: color?.white?.[700],
        brand: color?.primary?.[700],
        info: color?.blue?.[700],
        success: color?.green?.[600],
        warning: color?.orange?.[600],
        danger: color?.red?.[700],
        light: color?.white?.[100],
        dark: color?.black?.[100],
        'on-selected': color?.white?.[50],
        'on-selected-subtle': color?.blue?.[600],
        'on-inverse': color?.white?.[100],
        'on-brand': color?.white?.[50],
        'on-brand-subtle': color?.primary?.[700],
        'on-info': color?.white?.[50],
        'on-info-subtle': color?.blue?.[700],
        'on-onsuccess': color?.white?.[50],
        'on-success-subtle': color?.green?.[700],
        'on-warning': color?.white?.[50],
        'on-warning-subtle': color?.orange?.[700],
        'on-danger': color?.white?.[50],
        'on-danger-subtle': color?.red?.[700],
      },
      boxShadowColor: {
        raised: color?.white?.[300],
        overlay: color?.white?.[500],
        red: color?.red?.[500],
      },
      colors: {
        primary: {
          50: color?.primary?.[50],
          100: color?.primary?.[100],
          200: color?.primary?.[200],
          300: color?.primary?.[300],
          400: color?.primary?.[400],
          500: color?.primary?.[500],
          600: color?.primary?.[600],
          700: color?.primary?.[700],
          800: color?.primary?.[800],
          900: color?.primary?.[900],
          1000: color?.primary?.[1000],
          1100: color?.primary?.[1100],
        },
        green: {
          50: color?.green?.[50],
          100: color?.green?.[100],
          200: color?.green?.[200],
          300: color?.green?.[300],
          400: color?.green?.[400],
          500: color?.green?.[500],
          600: color?.green?.[600],
          700: color?.green?.[700],
          800: color?.green?.[800],
          900: color?.green?.[900],
          1000: color?.green?.[1000],
          1100: color?.green?.[1100],
        },
        blue: {
          50: color?.blue?.[50],
          100: color?.blue?.[100],
          200: color?.blue?.[200],
          300: color?.blue?.[300],
          400: color?.blue?.[400],
          500: color?.blue?.[500],
          600: color?.blue?.[600],
          700: color?.blue?.[700],
          800: color?.blue?.[800],
          900: color?.blue?.[900],
          1000: color?.blue?.[1000],
          1100: color?.blue?.[1100],
        },
        orange: {
          50: color?.orange?.[50],
          100: color?.orange?.[100],
          200: color?.orange?.[200],
          300: color?.orange?.[300],
          400: color?.orange?.[400],
          500: color?.orange?.[500],
          600: color?.orange?.[600],
          700: color?.orange?.[700],
          800: color?.orange?.[800],
          900: color?.orange?.[900],
          1000: color?.orange?.[1000],
          1100: color?.orange?.[1100],
        },
        red: {
          50: color?.red?.[50],
          100: color?.red?.[100],
          200: color?.red?.[200],
          300: color?.red?.[300],
          400: color?.red?.[400],
          500: color?.red?.[500],
          600: color?.red?.[600],
          700: color?.red?.[700],
          800: color?.red?.[800],
          900: color?.red?.[900],
          1000: color?.red?.[1000],
          1100: color?.red?.[1100],
        },
        black: {
          50: color?.black?.[50],
          100: color?.black?.[100],
          200: color?.black?.[200],
          300: color?.black?.[300],
          400: color?.black?.[400],
          500: color?.black?.[500],
          600: color?.black?.[600],
          700: color?.black?.[700],
          800: color?.black?.[800],
          900: color?.black?.[900],
          1000: color?.black?.[1000],
          1100: color?.black?.[1100],
        },
        white: {
          50: color?.white?.[50],
          100: color?.white?.[100],
          200: color?.white?.[200],
          300: color?.white?.[300],
          400: color?.white?.[400],
          500: color?.white?.[500],
          600: color?.white?.[600],
          700: color?.white?.[700],
          800: color?.white?.[800],
          900: color?.white?.[900],
          1000: color?.white?.[1000],
          1100: color?.white?.[1100],
        },
      },
      fontFamily: {
        sans: ['Inter', ...defaultTheme.fontFamily.sans],
      },
      fontSize: {
        xxxs: '0.60rem',
        xxs: '0.65rem',
      },
      spacing: {
        104: '26rem',
        112: '28rem',
        120: '30rem',
        130: '35rem',
        140: '40rem',
        150: '45rem',
        160: '50rem',
        170: '55rem',
        180: '60rem',
      },
      screens: {
        xs: { max: '320px' },
        '3xl': { min: '2560px' },
        ...defaultTheme.screens,
      },
    },
  },
  plugins: [
    cutomPlugins,
    tailwindForms({
      strategy: 'class',
    }),
    tailwindAnimation,
  ],
};
