import { BiJoystickButton } from 'react-icons/bi';

// import {
// HiCube,
// HiShieldExclamation,
// HiTemplate,
// HiTrendingUp,
// HiUsers,
// HiViewGrid,
// } from 'react-icons/hi';
import { TDirectory } from 'types';

import Buttons from 'features/buttons';

// import Dashboard from 'features/dashboard';
// import DashboardPartnerMng from 'features/dashboard-partner-mngt';
// import Transactions from 'features/transactions';
// import { WipContainer } from 'ui/components';

export const ADMIN_ROUTE_LIST: TDirectory[] = [
  {
    key: 'buttons',
    name: 'Buttons',
    icon: BiJoystickButton,
    component: Buttons,
    to: '/buttons',
    path: '/buttons',
    module_permissions: ['static-r'],
    group_by: 'main-menu',
    groups: [],
  },
  // {
  //   key: 'dashboard',
  //   name: 'Dashboard',
  //   icon: HiViewGrid,
  //   component: Dashboard,
  //   to: '/dashboard',
  //   path: '/dashboard',
  //   module_permissions: ['static-r'],
  //   group_by: 'main-menu',
  //   groups: [],
  // },
  // {
  //   key: 'transactions',
  //   name: 'Transactions',
  //   icon: HiTrendingUp,
  //   component: Transactions,
  //   to: '/transactions',
  //   path: '/transactions',
  //   module_permissions: ['static-r'],
  //   group_by: 'main-menu',
  //   groups: [],
  // },
  // {
  //   key: 'partner-mgmt',
  //   name: 'Partner Mgmt',
  //   icon: HiCube,
  //   component: undefined,
  //   to: '/partner-mgmt',
  //   path: '/partner-mgmt',
  //   module_permissions: ['static-r'],
  //   group_by: 'main-menu',
  //   groups: [
  //     {
  //       key: 'dashboard',
  //       name: 'Dashboard',
  //       module_permissions: ['static-r'],
  //       component: DashboardPartnerMng,
  //       to: '/dashboard',
  //       path: '/dashboard',
  //       group_by: 'main-menu',
  //       groups: [],
  //     },
  //     {
  //       key: 'partners',
  //       name: 'Partners',
  //       module_permissions: ['static-r'],
  //       component: WipContainer,
  //       to: '/partners',
  //       path: '/partners',
  //       group_by: 'main-menu',
  //       groups: [],
  //     },
  //   ],
  // },
  // {
  //   key: 'subscriber-mgmt',
  //   name: 'Subscriber Mgmt',
  //   icon: HiUsers,
  //   component: WipContainer,
  //   to: '/subscriber-mgmt',
  //   path: '/subscriber-mgmt',
  //   module_permissions: ['static-r'],
  //   group_by: 'main-menu',
  //   groups: [
  //     {
  //       key: 'dashboard',
  //       name: 'Dashboard',
  //       module_permissions: ['static-r'],
  //       component: WipContainer,
  //       to: '/dashboard',
  //       path: '/dashboard',
  //       group_by: '',
  //       groups: [],
  //     },
  //     {
  //       key: 'subscribers',
  //       name: 'Subscribers',
  //       module_permissions: ['static-r'],
  //       component: WipContainer,
  //       to: '/subscribers',
  //       path: '/subscribers',
  //       group_by: '',
  //       groups: [],
  //     },
  //     {
  //       key: 'applications',
  //       name: 'Applications',
  //       module_permissions: ['static-r'],
  //       component: WipContainer,
  //       to: '/applications',
  //       path: '/applications',
  //       group_by: '',
  //       groups: [],
  //     },
  //   ],
  // },
  // {
  //   key: 'user-management',
  //   name: 'User Management',
  //   icon: HiShieldExclamation,
  //   component: WipContainer,
  //   to: '/user-management',
  //   path: '/user-management',
  //   module_permissions: ['static-r'],
  //   group_by: 'admin-settings',
  //   groups: [
  //     {
  //       key: 'subscribers',
  //       name: 'Subscribers',
  //       module_permissions: ['static-r'],
  //       component: WipContainer,
  //       to: '/subscribers',
  //       path: '/subscribers',
  //       group_by: '',
  //       groups: [],
  //     },
  //     {
  //       key: 'administrators',
  //       name: 'Administrators',
  //       module_permissions: ['static-r'],
  //       component: WipContainer,
  //       to: '/administrators',
  //       path: '/administrators',
  //       group_by: '',
  //       groups: [],
  //     },
  //   ],
  // },
  // {
  //   key: 'content-management',
  //   name: 'Content Management',
  //   icon: HiTemplate,
  //   component: WipContainer,
  //   to: '/content-management',
  //   path: '/content-management',
  //   module_permissions: ['static-r'],
  //   group_by: 'admin-settings',
  //   groups: [],
  // },
];
